### ISSUE TITLE
How To Extract Csv File From Other Profile Folders AND Choose Where File is Saved

### ISSUE THREAD

**Issue by cytek04** [cfstras/chromecsv#2]
Hi,
I am wanting to create a cmd file and use chromecsv to extract a csv file of login data on multiple computers. But I found out that that path to Login Data is not always "%LOCALAPPDATA%\Google\Chrome\User Data\Default\Login Data". Depending on the users Chrome profile, it will sometimes put the file in a folder named Profile 1, Profile 2, or etc. inside User Data. I need a good way to make my cmd script get the Login Data file no matter which folder it is under inside User Data.

I also would like to be able to choose where to save the output file. If this is possible what is the command?

I appreciate your answer if you can help me. Thanks in advance!

**Comment by cfstras** [comment]
For changing the output filename, there's a hardcoded variable `outputFile` in [main.go](../blob/master/main.go). You'll have to change that, either manually or replace it with something like `os.Args[2]`.

For finding the right path, you could either extend the script to take the path `%LOCALAPPDATA%\Google\Chrome\User Data\Default` and then iterate through all profiles (Default, Profile 1, Profile 2, ...) instead of just taking one.

**Comment by cytek04** [comment]
Ok. Thanks. I am new to programming and I will see what I can do. Hopefully I can make it work. If you want to, it would help if you could send the code to make it iterate through all profiles. Thanks so much for helping.
